#! /bin/bash

MODSECKEY="./signing_key.priv"
MODPUBKEY="./signing_key.x509"
moddir=$1

modules=`find $moddir -type f -name '*.ko'`

for mod in $modules
do
    ./scripts/sign-file sha256 $MODSECKEY $MODPUBKEY $mod
    rm -f $mod.sig $mod.dig
done

RANDOMMOD=$(echo "$modules" | sort -R | tail -n 1)
if [ "~Module signature appended~" != "$(tail -c 28 $RANDOMMOD)" ]; then
	echo "*** Modules are unsigned! ***"
	exit 1
fi

exit 0
